# Generated by Django 4.0.5 on 2022-06-07 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.RemoveField(
            model_name='konselor',
            name='akun',
        ),
        migrations.RemoveField(
            model_name='konsultasirecord',
            name='konselor',
        ),
        migrations.RemoveField(
            model_name='konsultasirecord',
            name='pasien',
        ),
        migrations.RemoveField(
            model_name='moodtracking',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='moodtracking',
            name='pasien',
        ),
        migrations.RemoveField(
            model_name='paketobat',
            name='akun',
        ),
        migrations.RemoveField(
            model_name='paketobat',
            name='obat',
        ),
        migrations.RemoveField(
            model_name='pasien',
            name='akun',
        ),
        migrations.DeleteModel(
            name='Akun',
        ),
        migrations.DeleteModel(
            name='Konselor',
        ),
        migrations.DeleteModel(
            name='KonsultasiRecord',
        ),
        migrations.DeleteModel(
            name='Mood',
        ),
        migrations.DeleteModel(
            name='MoodTracking',
        ),
        migrations.DeleteModel(
            name='Obat',
        ),
        migrations.DeleteModel(
            name='PaketObat',
        ),
        migrations.DeleteModel(
            name='Pasien',
        ),
    ]
