# Generated by Django 4.0.5 on 2022-06-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_akun_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='dokter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
